services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: jongmin
      POSTGRES_PASSWORD: ${MY_DB_PASSWORD}
      POSTGRES_DB: sandbox_db
    networks:
      - isolated
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jongmin -d sandbox_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    user: root
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"
    environment:
      - SPARK_MASTER_HOST=0.0.0.0
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8081
    ports:
      - "7077:7077"
      - "8081:8081"
    networks:
      - isolated
      - default
    volumes:
      - ./dags:/opt/spark-apps

  spark-worker:
    image: apache/spark:latest
    container_name: spark-worker-1
    user: root
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_WEBUI_PORT=8081
    depends_on:
      - spark-master
    networks:
      - isolated
    volumes:
      - ./dags:/opt/spark-apps

  jupyter-local:
    build: .
    env_file:
      - .env
    command: python -m jupyterlab --ip "0.0.0.0" --no-browser --NotebookApp.token='' --allow-root
    environment:
      SPARK_DRIVER_BIND_ADDRESS: 0.0.0.0
      SPARK_DRIVER_HOST: jupyter-local
      SPARK_DRIVER_PORT: 29200
    expose:
      - 29200
    ports:
      - 8888:8888
      - 4040:4040
    networks:
      - isolated
      - default
    volumes:
      - ./dags:/opt/spark-apps
      - ~/.aws:/root/.aws:ro

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-webserver:8080/execution/'
      AIRFLOW__API_AUTH__JWT_SECRET: ${MY_JWT_SECRET}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://jongmin:${MY_DB_PASSWORD}@postgres:5432/sandbox_db
      _PIP_ADDITIONAL_REQUIREMENTS: "pyspark==3.5.0 boto3 pendulum"
    command: ["airflow", "api-server"]
    ports:
      - "8080:8080"
    networks:
      - default
      - isolated
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-webserver:8080/execution/'
      AIRFLOW__API_AUTH__JWT_SECRET: ${MY_JWT_SECRET}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://jongmin:${MY_DB_PASSWORD}@postgres:5432/sandbox_db
      _PIP_ADDITIONAL_REQUIREMENTS: "pyspark==3.5.0 boto3 pendulum"
      AWS_PROFILE: data-eng
      S3_BUCKET_ARN: ${S3_BUCKET_ARN}
      JAVA_HOME: /usr/lib/jvm/default-java
    command: ["airflow", "scheduler"]
    networks:
      - isolated
      - default
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ~/.aws:/home/airflow/.aws:ro
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-dag-processor:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-webserver:8080/execution/'
      AIRFLOW__API_AUTH__JWT_SECRET: ${MY_JWT_SECRET}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://jongmin:${MY_DB_PASSWORD}@postgres:5432/sandbox_db
      _PIP_ADDITIONAL_REQUIREMENTS: "pyspark==3.5.0 boto3 pendulum"
      AWS_PROFILE: data-eng
      S3_BUCKET_ARN: ${S3_BUCKET_ARN}
    command: ["airflow", "dag-processor"]
    networks:
      - isolated
      - default
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ~/.aws:/home/airflow/.aws:ro
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-webserver:8080/execution/'
      AIRFLOW__API_AUTH__JWT_SECRET: ${MY_JWT_SECRET}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://jongmin:${MY_DB_PASSWORD}@postgres:5432/sandbox_db
      _PIP_ADDITIONAL_REQUIREMENTS: "pyspark==3.5.0 boto3 pendulum"
    command:
      - bash
      - -c
      - |
        airflow db migrate
        airflow users create \
          --username admin \
          --firstname Jongmin \
          --lastname Hwang \
          --role Admin \
          --email ${AIRFLOW_EMAIL} \
          --password ${AIRFLOW_PASSWORD}
    networks:
      - isolated
      - default
    depends_on:
      postgres:
        condition: service_healthy

  bastion:
    image: alpine:latest
    command: sh -c "apk add --no-cache socat && socat TCP-LISTEN:5433,fork,reuseaddr TCP:postgres:5432"
    ports:
      - "5433:5433"
    networks:
      - default
      - isolated
    depends_on:
      - postgres

networks:
  isolated:
    internal: true

volumes:
  pg_data:
    driver: local