services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: jongmin
      POSTGRES_PASSWORD: ${MY_DB_PASSWORD}
      POSTGRES_DB: sandbox_db
    networks:
      - isolated
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jongmin -d sandbox_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  airflow-webserver:
    image: apache/airflow:latest
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-webserver:8080/execution/'
      AIRFLOW__API_AUTH__JWT_SECRET: ${MY_JWT_SECRET}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://jongmin:${MY_DB_PASSWORD}@postgres:5432/sandbox_db
    command: ["airflow", "api-server"]
    ports:
      - "8080:8080"
    networks:
      - default
      - isolated
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
  
  airflow-scheduler:
    image: apache/airflow:latest
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-webserver:8080/execution/'
      AIRFLOW__API_AUTH__JWT_SECRET: ${MY_JWT_SECRET}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://jongmin:${MY_DB_PASSWORD}@postgres:5432/sandbox_db
      AWS_PROFILE: data-eng
    command: ["airflow", "scheduler"]
    networks:
      - default
      - isolated
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ~/.aws:/home/airflow/.aws:ro
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-dag-processor:
      image: apache/airflow:latest
      env_file:
        - .env
      environment:
        AIRFLOW__CORE__EXECUTOR: LocalExecutor
        AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
        AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-webserver:8080/execution/'
        AIRFLOW__API_AUTH__JWT_SECRET: ${MY_JWT_SECRET}
        AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://jongmin:${MY_DB_PASSWORD}@postgres:5432/sandbox_db
        AWS_PROFILE: data-eng
      command: ["airflow", "dag-processor"]
      networks:
        - default
        - isolated
      volumes:
        - ./dags:/opt/airflow/dags
        - ./logs:/opt/airflow/logs
        - ~/.aws:/home/airflow/.aws:ro
      depends_on:
        postgres:
          condition: service_healthy
        airflow-init:
          condition: service_completed_successfully
  
  airflow-init:
    image: apache/airflow:latest
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-webserver:8080/execution/'
      AIRFLOW__API_AUTH__JWT_SECRET: ${MY_JWT_SECRET}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://jongmin:${MY_DB_PASSWORD}@postgres:5432/sandbox_db
    command:
      - bash
      - -c
      - |
        airflow db migrate
        airflow users create \
          --username admin \
          --firstname Jongmin \
          --lastname Hwang \
          --role Admin \
          --email ${AIRFLOW_EMAIL} \
          --password ${AIRFLOW_PASSWORD}
    networks:
      - isolated
    depends_on:
      postgres:
        condition: service_healthy

  bastion:
    image: alpine:latest
    command: sh -c "apk add --no-cache socat && socat TCP-LISTEN:5433,fork,reuseaddr TCP:postgres:5432"
    ports:
      - "5433:5433"
    networks:
      - default
      - isolated
    depends_on:
      - postgres

networks:
  isolated:
    internal: true

volumes:
  pg_data:
    driver: local